#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/9707bcc7-edc4-4738-9dab-8950f6520c20 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int servo1;
  int servo2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h> 
Servo myservo1, myservo2;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
myservo1.attach(0);
myservo2.attach(2);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  //servomotorcontroller = map(servo, 0, 1023, 0, 180); 
  myservo1.write(servo1);
  myservo2.write(servo2);
}


/*
  Since Servo is READ_WRITE variable, onServoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onServoChange()  {
  // Add your code here to act upon Servo change
  
  
}


/*
  Since Servo1 is READ_WRITE variable, onServo1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onServo1Change()  {
  // Add your code here to act upon Servo1 change
}

/*
  Since Servo2 is READ_WRITE variable, onServo2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onServo2Change()  {
  // Add your code here to act upon Servo2 change
}
