/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/803c5e9e-4917-4092-aa83-6b3cf15b3236 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool motionDetected;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const int motionSensorPin = 2;   // Pin connected to the Motion sensor
const int ledPin = 5;
const int buzzerPin = 4; // Pin connected to the buzzer
bool isMotionDetected = false;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Set motionSensorPin as input
  pinMode(motionSensorPin, INPUT);

  // Set LEDPin as output
  pinMode(ledPin, OUTPUT);

  // Set buzzerPin as output
  pinMode(buzzerPin, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

  bool isMotion = digitalRead(motionSensorPin);
  Serial.print("IsMotion");
  Serial.println(isMotion);
  // Check if motion is detected
  if (!isMotion == true ) {
    motionDetected = true; // Update the motionDetected property directly
    isMotionDetected = true;
    sendMotionStatus(true);
    activateLED(true);
    activateBuzzer(true);

  } else if (!isMotion == false) {
    motionDetected = false; // Update the motionDetected property directly
    isMotionDetected = false;
    sendMotionStatus(false);
    activateLED(false);
    activateBuzzer(false);

  }

  delay(1000); // Delay to avoid excessive checks
  
  
}

void sendMotionStatus(bool motionDetected)
{

  if (motionDetected)
  {
    Serial.println("Motion detected! Sending alert to server..."); // Send a message indicating motion is detected
    motionDetected = true;
  }
  else {

    Serial.println("Motion not detected."); // Send a message indicating motion is not detected
    motionDetected = false;
  }
}

void activateBuzzer(bool activate) {
  if (activate) {
    // Turn on the buzzer
    digitalWrite(buzzerPin, HIGH);
  } else {
    // Turn off the buzzer
    digitalWrite(buzzerPin, LOW);
  }
}

void activateLED(bool activate) {
  if (activate) {
    // Turn on the buzzer
    digitalWrite(ledPin, HIGH);
  } else {
    // Turn off the buzzer
    digitalWrite(ledPin, LOW);
  }
}


/*
  Since MotionDetected is READ_WRITE variable, onMotionDetectedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotionDetectedChange()  {
  // Add your code here to act upon MotionDetected change
}
